FROM alpine:edge

ADD sqlite3-nodejs.tar.gz /ghost/node_modules/
ADD start.bash /ghost-start

RUN echo "http://nl.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories && \
    apk add --update wget nodejs && \
    apk upgrade && \
    wget -q --no-check-certificate https://ghost.org/zip/ghost-latest.zip -O /tmp/ghost.zip && \
    unzip -q /tmp/ghost.zip -d /ghost && \
    cd /ghost && \
    npm install --production && \
    sed 's/127.0.0.1/0.0.0.0/' /ghost/config.example.js > /ghost/config.js && \
    adduser ghost -D -h /ghost -s /bin/sh && \
    npm cache clean && \
    rm -rf /var/cache/apk/* /tmp/*

ENV NODE_ENV production
VOLUME ["/data", "/ghost-override"]
WORKDIR /ghost
CMD ["sh", "/ghost-start"]
EXPOSE 2368
