FROM alpine:edge

RUN echo "http://nl.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories && \
    apk update && \
    apk add --update nodejs python make gcc libc-dev g++ && \
    cd /tmp && \
    npm install sqlite3 --build-from-source && \
    cd /tmp/node_modules && \
    tar czf sqlite3-nodejs.tar.gz sqlite3
    
VOLUME /sqlite3
WORKDIR /tmp/node_modules
